name: child_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # HTTP & API
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1

  # State Management
  provider: ^6.1.1

  # Location Services
  geolocator: ^10.1.0
  location: ^5.0.3

  # Permissions
  permission_handler: ^11.2.0

  # Background Services - ✅ Updated to latest versions
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.2.2

  # Real-time Communication
  pusher_channels_flutter: ^2.2.1
  web_socket_channel: ^2.4.0

  # Local Storage
  shared_preferences: ^2.2.2
  encrypted_shared_preferences: ^3.0.1

  # Screen Capture
  flutter_screen_recording: ^2.0.3
  screenshot: ^2.1.0

  # Notification Handling
  notification_listener_service: ^0.3.0
  flutter_local_notifications: ^16.3.2

  # Device Info & Security
  device_info_plus: ^9.1.1
  crypto: ^3.0.3

  # Emergency Features
  url_launcher: ^6.2.2
  vibration: ^1.8.4

  # UI & Animation
  cupertino_icons: ^1.0.6
  lottie: ^2.7.0
  animations: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  bloc_test: ^9.1.5

flutter:
  uses-material-design: true
