name: child_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # HTTP & API
  dio: ^5.9.0
  retrofit: ^4.7.2
  json_annotation: ^4.9.0

  # State Management
  provider: ^6.1.5+1

  # Location Services - ✅ Stable versions that work together
  geolocator: ^14.0.2
  location: ^8.0.1

  # Permissions - ✅ Compatible version
  permission_handler: ^12.0.1

  # Background Services - ✅ Stable version
  flutter_background_service: ^5.1.0

  # Real-time Communication
  pusher_channels_flutter: ^2.5.0
  web_socket_channel: ^3.0.3

  # Local Storage
  shared_preferences: ^2.5.3

  # Screen Capture
  screenshot: ^3.0.0

  # Notification Handling
  flutter_local_notifications: ^19.4.1

  # Device Info & Security
  device_info_plus: ^11.5.0
  crypto: ^3.0.6

  # Emergency Features
  url_launcher: ^6.3.2
  vibration: ^3.1.3

  # UI & Animation
  cupertino_icons: ^1.0.8
  lottie: ^3.3.1
  animations: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.7.0
  json_serializable: ^6.11.0

flutter:
  uses-material-design: true
